name: Wiki Sync

on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/**'
    branches:
      - main

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    name: Wiki sync
    steps:
      - uses: OrlovM/Wiki-Action@v1
        with:
          path: 'docs'
          token: ${{ secrets.GH_TOKEN }}
